define OWNAS = 152873;
define IPV4_BORDER_IP = 43.229.16.1;
define IPV6_BORDER_IP = 2402:2f60:ffff::1;

router id IPV4_BORDER_IP;

log syslog { info, remote, warning, error, debug, auth, fatal, bug };
log stderr all;
debug protocols {events, states, interfaces};
graceful restart wait 15;

protocol device {
    scan time 10;
}

include "ipv4.conf";
include "ipv6.conf";
