ipv4 table bgp_v4;
ipv4 table ospf_v4;
ipv4 table kernel_v4;

protocol direct direct_v4 {
    ipv4 {
        table kernel_v4;
    };
}

protocol kernel v4_kernel {
    ipv4 {
        table kernel_v4;
        import none;
        export filter {
            accept;
        };
    };
    learn on;
    scan time 10;
    graceful restart on;
}

protocol static static_kernel_v4 {
    ipv4 {
        table kernel_v4;
        import all;
        export none;
    };
}

protocol static static_bgp_v4 {
    ipv4 {
        table bgp_v4;
        import filter {
            bgp_large_community.add((OWNAS, 100, 1));
            accept;
        };
        export none;
    };
    route 43.229.16.0/23 blackhole;
}

protocol static static_ospf_v4 {
    ipv4 {
        table ospf_v4;
        import all;
        export none;
    };
    route 0.0.0.0/0 blackhole;
}

protocol ospf v2 {
    ecmp off;
    ipv4 {
        table ospf_v4;
        import filter {
            if net = 0.0.0.0/0 then reject;
            accept;
        };
        export filter {
            if source = RTS_BGP then reject;
            accept;
        };
    };
    area 0.0.0.0 {
        stubnet 43.229.16.1/32;
        interface "lo" {
            stub on;
        };
        interface "eth2" {
            type broadcast;
        };
        interface "eth3" {
            type broadcast;
        };
    };
}

template bgp bgp_upstream_template {
    local 163.220.192.59 as OWNAS;
    keepalive time 10;
    hold time 30;
    default bgp_local_pref 200;
    ipv4 {
        table bgp_v4;
        igp table kernel_v4;
        next hop self;
        import filter {
            if bgp_path.len > 24 then reject;
            if (net.len < 8) || (net.len > 24) then reject;
            if bgp_path = [0, 23456, 64496..64511, 64512..65534, 65535, 65536..65551, 65552..131071, 4200000000..4294967294, 4294967295] then reject;
            if bgp_path = [ 174, 209, 701, 702, 1239, 1299, 2914, 3257, 3320, 3356, 3491, 3549, 3561, 4134, 5511, 6453, 6461, 6762, 6830, 7018] then reject;
            if net ~ [10.0.0.0/8+, 192.168.0.0/16+, 172.16.0.0/12+] then reject;
            bgp_local_pref = 200;
            accept;
        };
        export filter {
            if proto = "static_bgp_v4" then accept;
            reject;
        };
    };
}

protocol bgp upstream_sdcc from bgp_upstream_template {
    neighbor 163.220.192.17 as 38074;
}

protocol bgp upstream_homenoc from bgp_upstream_template {
    neighbor 163.220.192.36 as 59105;
}

template bgp bgp_local_template {
    local IPV4_BORDER_IP as OWNAS;
    neighbor as OWNAS;
    default bgp_local_pref 100;
    ipv4 {
        table bgp_v4;
        igp table kernel_v4;
        import filter {
            bgp_local_pref = 100;
            accept;
        };
        export filter {
            if bgp_path.first != OWNAS then accept;
            if (152873, 200, 300) ~ bgp_large_community then {
                bgp_local_pref = 300;
                accept;
            }
            reject;
        };
        next hop self;
    };
}

protocol bgp bgp_local_1 from bgp_local_template {
    neighbor 43.229.16.4;
} 

protocol bgp bgp_local_2 from bgp_local_template {
    neighbor 43.229.16.2;
}

protocol pipe bgp2kernel {
    table bgp_v4;
    peer table kernel_v4;
    import none;
    export filter {
        if proto = "static_bgp_v4" then reject;
        if bgp_path.first = OWNAS then {
            if bgp_large_community ~ (OWNAS, 100, 1) then reject;
        }
        accept;
    };
}

protocol pipe ospf2kernel {
    table ospf_v4;
    peer table kernel_v4;
    import filter {
        if source = RTS_BGP then reject;
        accept;
    };
    export filter {
        if proto = "static_ospf_v4" then reject;
        accept;
    };
}
