ipv6 table bgp_v6;
ipv6 table ospf_v6;
ipv6 table kernel_v6;

protocol direct direct_v6 {
    ipv6 {
        table kernel_v6;
    };
}

protocol kernel proto_kernel_v6 {
    ipv6 {
        table kernel_v6;
        import none;
        export filter {
            accept;
        };
    };
    learn on;
    scan time 10;
    graceful restart on;
}

protocol static static_kernel_v6 {
    ipv6 {
        table kernel_v6;
        import all;
        export none;
    };
}

protocol static static_bgp_v6 {
    ipv6 {
        table bgp_v6;
        import filter {
            bgp_large_community.add((OWNAS, 100, 1));
            accept;
        };
        export none;
    };
    route 2402:2f60::/32 blackhole;
}

protocol static static_ospf_v6 {
    ipv6 {
        table ospf_v6;
        import all;
        export none;
    };
    route ::/0 blackhole;
}

protocol ospf v3 {
    ecmp off;
    ipv6 {
        table ospf_v6;
        import filter {
            if net = ::/0 then reject;
            accept;
        };
        export filter {
            if source = RTS_BGP then reject;
            accept;
        };
    };
    area 0.0.0.0 {
        stubnet 2402:2f60:ffff::1/128;
        interface "lo" {
            stub on;
        };
        interface "eth2" {
            type broadcast;
        };
        interface "eth3" {
            type broadcast;
        };
    };
}

template bgp bgp_v6_upstream_template {
    local 2401:5e40:c600::15:2873:1 as OWNAS;
    keepalive time 10;
    hold time 30;
    default bgp_local_pref 200;
    ipv6 {
        table bgp_v6;
        igp table kernel_v6;
        next hop self;
        import filter {
            if bgp_path.len > 24 then reject;
            if (net.len < 16) || (net.len > 48) then reject;
            if bgp_path = [0, 23456, 64496..64511, 64512..65534, 65535, 65536..65551, 65552..131071, 4200000000..4294967294, 4294967295] then reject;
            if bgp_path = [ 174, 209, 701, 702, 1239, 1299, 2914, 3257, 3320, 3356, 3491, 3549, 3561, 4134, 5511, 6453, 6461, 6762, 6830, 7018] then reject;
            if net ~ [3ffe::/16+, 2001:db8::/32+, 2001::/33+, 2002::/17+, 0000::/8+, fe00::/8+,  ::/128-, ::/0{0,15}, ::/0{64,128}] then reject;
            accept;
        };
        export filter {
            if proto = "static_bgp_v6" then accept;
            reject;
        };
    };
}

protocol bgp upstream_v6_homenoc from bgp_v6_upstream_template {
    neighbor 2401:5e40:c600::5:9105:1 as 59105;
}

template bgp bgp_v6_local_template {
    local IPV6_BORDER_IP as OWNAS;
    neighbor as OWNAS;
    default bgp_local_pref 100;
    ipv6 {
        table bgp_v6;
        igp table kernel_v6;
        import filter {
            bgp_local_pref = 100;
            accept;
        };
        export filter {
            if bgp_path.first != OWNAS then accept;
            reject;
        };
        next hop self;
    };
}

protocol bgp bgp_v6_local_1 from bgp_v6_local_template {
    neighbor 2402:2f60:ffff::4;
}

protocol bgp bgp_v6_local_2 from bgp_v6_local_template {
    neighbor 2402:2f60:ffff::2;
}

protocol pipe v6_bgp2kernel {
    table bgp_v6;
    peer table kernel_v6;
    import none;
    export filter {
        if proto = "static_bgp_v6" then reject;
        if bgp_path.first = OWNAS then {
            if bgp_large_community ~ (OWNAS, 100, 1) then reject;
        }
        accept;
    };
}

protocol pipe v6_ospf2kernel {
    table ospf_v6;
    peer table kernel_v6;
    import filter {
        if source = RTS_BGP then reject;
        accept;
    };
    export filter {
        if proto = "static_ospf_v6" then reject;
        accept;
    };
}
