roa4 table r4;
roa6 table r6;

protocol rpki MAIN_RPKI {
    roa4 { table r4; };
    roa6 { table r6; };
    remote 10.0.0.101 port 8083;
    retry keep 90;
    refresh keep 900;
    expire keep 172800;
}
